from __future__ import annotations

_UNIT_PROGRESSION_SCHEMA_VERSION = "v1"
_DECISION_SCHEMA_VERSION = "v1"
_CHECKPOINT_SCHEMA_VERSION = "v1"
_RUN_STATE_SCHEMA_VERSION = "v1"
_COMMIT_EXECUTION_SCHEMA_VERSION = "v1"
_PUSH_EXECUTION_SCHEMA_VERSION = "v1"
_PR_EXECUTION_SCHEMA_VERSION = "v1"
_MERGE_EXECUTION_SCHEMA_VERSION = "v1"
_ROLLBACK_EXECUTION_SCHEMA_VERSION = "v1"

__all__ = [
    "_CHECKPOINT_SCHEMA_VERSION",
    "_COMMIT_EXECUTION_SCHEMA_VERSION",
    "_DECISION_SCHEMA_VERSION",
    "_MERGE_EXECUTION_SCHEMA_VERSION",
    "_PR_EXECUTION_SCHEMA_VERSION",
    "_PUSH_EXECUTION_SCHEMA_VERSION",
    "_ROLLBACK_EXECUTION_SCHEMA_VERSION",
    "_RUN_STATE_SCHEMA_VERSION",
    "_UNIT_PROGRESSION_SCHEMA_VERSION",
]
